spring:
  datasource:
    driver-clas-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_ENDPOINT_URL}:3306/${DATABASE_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

    config:
      import: application-secret.properties
      activate:
        on-profile: dev
chatgpt:
  api-key: ${GPT_OPENAPI_KEY}
  temperature: 1
  max_token: 256
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0

server:
  port: 8082